### ISSUE TITLE
Tests do not compile with Rust 1.0.0

### ISSUE THREAD

**Issue by andresv** [tkellogg/rust-mqtt#1]
```
rustc -V
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)

cargo build
#ok

cargo test
tests/client_tests.rs:50:8: 50:14 error: `client` does not live long enough
tests/client_tests.rs:50    match client.connect() {
                                  ^~~~~~
tests/client_tests.rs:39:32: 54:2 note: reference must be valid for the lifetime 'a as defined on the block at 39:31...
tests/client_tests.rs:39 fn connect<'a>() -> Client<'a> {
tests/client_tests.rs:40    let mut client = Client {
tests/client_tests.rs:41        options : ConnectOptions {
tests/client_tests.rs:42            host_port: "localhost:1883",
tests/client_tests.rs:43            client_id: "rust-test",
tests/client_tests.rs:44            clean: true,
                         ...
tests/client_tests.rs:48:4: 54:2 note: ...but borrowed value is only valid for the block suffix following statement 0 at 48:3
tests/client_tests.rs:48    };
tests/client_tests.rs:49
tests/client_tests.rs:50    match client.connect() {
tests/client_tests.rs:51        Ok(()) => client,
tests/client_tests.rs:52        Err(e) => panic!(e)
tests/client_tests.rs:53    }
                         ...
error: aborting due to previous error
tests/parser_tests.rs:13:35: 13:42 error: type `std::net::tcp::TcpStream` does not implement any method in scope named `clone`
tests/parser_tests.rs:13    let mut socket_readable = socket.clone();
                                                             ^~~~~~~
tests/parser_tests.rs:17:23: 17:52 error: type `std::net::tcp::TcpStream` does not implement any method in scope named `write`
tests/parser_tests.rs:17    let mut res = socket.write(connect_buf.as_slice());
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tests/parser_tests.rs:17:23: 17:52 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
tests/parser_tests.rs:17:23: 17:52 help: candidate #1: use `std::io::Write`
tests/parser_tests.rs:18:32: 18:39 error: type `std::net::tcp::TcpStream` does not implement any method in scope named `flush`
tests/parser_tests.rs:18    res = res.and_then(|_| socket.flush());
                                                          ^~~~~~~
tests/parser_tests.rs:18:32: 18:39 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
tests/parser_tests.rs:18:32: 18:39 help: candidate #1: use `std::io::Write`
tests/parser_tests.rs:22:20: 22:27 error: mismatched types:
 expected `_`,
    found `core::ops::RangeTo<_>`
(expected integral variable,
    found struct `core::ops::RangeTo`) [E0308]
tests/parser_tests.rs:22    let mut buf = [0, ..1024];
...
...
```

**Comment by tkellogg** [comment]
woo! my first issue on this repo! Yes, I've been working on it. I don't think I've gotten it fully working yet. If I push my current changes, would you want to fix it the rest of the way?

**Comment by andresv** [comment]
Not sure, I do not know how difficult it might be. However I guess half solution is better than no solution, so go ahead.

**Comment by tkellogg** [comment]
k, pushed. All that's left is lifetime issues during the tests. Feel free to send a PR if you get it working. Otherwise I'll probably get to it in a couple weeks

**Comment by joewilliams** [comment]
I am running into the same issue, https://gist.github.com/joewilliams/dc6d814401b899faf66f

**Comment by andresv** [comment]
I wrote a wrapper around MQTT C library. You could give it a try: https://github.com/cubehub/rust-mqtt

**Comment by tkellogg** [comment]
Tests now compile and pass
